apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "etcd.labels" . | nindent 4 }}
  name: {{ include "etcd.serviceName" . }}
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - port: {{ .Values.clientPort }}
      name: etcd-client-ssl
    - port: {{ .Values.peerApiPort }}
      name: etcd-server-ssl
    - port: {{ .Values.metricsPort }}
      name: metrics
  selector:
    {{- include "etcd.selectorLabels" . | nindent 4 }}
