apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "etcd.fullname" . }}-selfsigned-issuer
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "etcd.labels" . | nindent 4 }}
spec:
  selfSigned: {}